[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://demo-mode-disabled"
  REACT_APP_DEMO_MODE = "true"
  CI = "false"
  NODE_VERSION = "18"