[build]
  publish = "."
  command = "echo 'Using pre-built files from repository'"

[[redirects]]
  from = "/api/*"
  to = "https://tms-prototype-production.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "https://tms-prototype-production.up.railway.app/uploads/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://tms-prototype-production.up.railway.app"
  CI = "false"