[build]
  publish = "client/build"
  command = "cd client && npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://35izoi3ebh.execute-api.us-east-1.amazonaws.com/prod"
  CI = "false"
  NODE_VERSION = "18.x"
  NPM_VERSION = "10.x"