services:
  - type: web
    name: tms-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://andi_db_user:mfVEIDLWYj04uBPU@cluster0.cnhkiiz.mongodb.net/tms?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: your_super_secure_jwt_secret_key_here_2024
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: REFRESH_TOKEN_SECRET
        value: your_refresh_token_secret_key_here_2024
      - key: REFRESH_TOKEN_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: https://overdrivetms2025.netlify.app,http://localhost:3000
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_PATH
        value: ./uploads
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: BCRYPT_SALT_ROUNDS
        value: 12